var a : int[5] = [[1, 2, 3], [4, 5, 6], [7, 8, 9]];

a[2];

while (5 > 4) {
  const a = 13;
}

for (var i = 0; i < 10; i += 1) {
  const b = 2;
}

func add(a: int, b: int) int {
  return a + b;
}

func actual() void {
}

const a: int = 10 + 5;


add(1, a, 3, 2*4, actual());

"hello, world";

var l: int = a * 2 / 3;
const is: bool = true;
var w: int = (10 + 2) - 4;

var i: int = 0;
if (a == 2) {
  i = 10;
} else {
  i = 4;
}


